
[colors.primary]
background = '0x282828'
foreground = '0xd4be98'

[colors.normal]
black   = '0x3c3836'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
black   = '0x3c3836'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.selection]
background = '0x2d4f67'
foreground = '0xc8c093'

[[colors.indexed_colors]]
index = 16
color = '0xffa066'

[[colors.indexed_colors]]
index = 17
color = '0xff5d62'


[font]
size = 20.0


[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window]
opacity = 0.85
